helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

repositories:
  #  - name: percona
  #    url: https://percona.github.io/percona-helm-charts
  #  - name: bitnami
  #    url: https://charts.bitnami.com/bitnami
  - name: stackable
    url: https://repo.stackable.tech/repository/helm-stable

helmfiles:
  #  - path: perconapg/helmfile.yaml
  - path: ./stackable/helmfile.yaml
  - path: ./trino/helmfile.yaml
